/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	env: {
		NEXT_PUBLIC_GOOGLE_ANALYTICS: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS,
		NEXT_PUBLIC_GOOGLE_TAGS_MANAGER: process.env.NEXT_PUBLIC_GOOGLE_TAGS_MANAGER,
		NEXT_PUBLIC_WHATSAPP_NUMBER: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER,
		NEXT_PUBLIC_ID_SHEET_CATEGORIES: process.env.NEXT_PUBLIC_ID_SHEET_CATEGORIES,
		NEXT_PUBLIC_GOOGLE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_API_KEY,
		NEXT_PUBLIC_FACEBOOK_VERIFICATION: process.env.NEXT_PUBLIC_FACEBOOK_VERIFICATION,
	},
};

module.exports = nextConfig;
