import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Button from "@/commons/Button";
import Layout from "@/components/Layout";
import { FC } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          width={100}
          height={24}
          priority
        />
        <Button>Pruebs</Button>
      </Layout>
    </>
  );
};

export default Home;
