import Head from 'next/head';
import { Inter } from '@next/font/google';
import Layout from '@/components/Layout';
import HomeView from './Home';

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout >       
        <HomeView />            
      </Layout>
    </>
  )
};

export default Home;
