import { FC } from "react";
import Head from "next/head";
import HomeView from "./Home";
import { Inter } from "@next/font/google";
import Layout from "@/components/Layout";

// const inter = Inter({ subsets: ["latin"] });

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Renúver</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeView />
      </Layout>
    </>
  );
};

export default Home;
